WORK_DIR = $(shell pwd)
NEMU_HOME = $(WORK_DIR)/nemu
V_SRC_HOME = $(WORK_DIR)/vsrc
CC_SRC_HOME = $(WORK_DIR)/csrc

# config
VERILATOR = verilator
CC = clang
CXX = clang++

# Include variables and rules generated by menuconfig
-include $(WORK_DIR)/config/auto.conf
-include $(WORK_DIR)/config/auto.conf.cmd

include $(WORK_DIR)/scripts/config.mk
include $(WORK_DIR)/scripts/build.mk

# difftest
DIFF_REF_DIR = $(NEMU_HOME)
DIFF_SO = $(DIFF_REF_DIR)/build/riscv64-nemu-interpreter-so
# DIFF_SO = $(DIFF_REF_DIR)/tools/spike-diff/build/riscv64-spike-so

$(DIFF_SO):
	$(MAKE) -s -C $(DIFF_REF_DIR)

override ARGS ?= --log=$(BUILD_DIR)/log.txt --diff=$(DIFF_SO)
IMG ?=

run-env: $(BIN) $(DIFF_SO)

run: run-env
	$(BIN) $(ARGS) $(IMG)

lldb: run-env
	lldb $(BIN) -- $(ARGS) $(IMG)

clean:
	-rm -rf $(BUILD_DIR)/*

.PHONY: run lldb clean run-env
